const express = require('express');
const router = express.Router();

const authRoutes = require('./auth');
const userRoutes = require('./users');
const contentRoutes = require('./content');
const messageRoutes = require('./messages');
const friendRoutes = require('./friends');
const searchRoutes = require('./search');
const moderationRoutes = require('./moderation');
const pushRoutes = require('./push');
const settingsRoutes = require('./settings');
const recommendationsRoutes = require('./recommendations');
const onboardingRoutes = require('./onboarding');
const complianceRoutes = require('./compliance');
const sessionRoutes = require('./sessions');
const spotifyRoutes = require('./spotify');
const billingRoutes = require('./billing');
const trustRoutes = require('./trust');
const paymentsRoutes = require('./payments');
const uploadRoutes = require('./upload');
const emailRoutes = require('./email');
const wimpyRoutes = require('./wimpy');
const imagesRoutes = require('./images');
const passwordResetRoutes = require('./password-reset');
const healthRoutes = require('./health');
const profileRoutes = require('./profile');
const streakRoutes = require('./streaks');
const scoresRoutes = require('./scores');
const debugRoutes = require('./debug');
const friendRequestRoutes = require('./friend-requests');

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/password', passwordResetRoutes);
router.use('/friend-requests', friendRequestRoutes);
router.use('/profile', profileRoutes);
router.use('/streaks', streakRoutes);
router.use('/scores', scoresRoutes);
router.use('/debug', debugRoutes);
router.use('/users', userRoutes);
router.use('/', contentRoutes);
router.use('/messages', messageRoutes);
router.use('/friends', friendRoutes);
router.use('/search', searchRoutes);
router.use('/moderation', moderationRoutes);
router.use('/push', pushRoutes);
router.use('/settings', settingsRoutes);
router.use('/recommendations', recommendationsRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/compliance', complianceRoutes);
router.use('/sessions', sessionRoutes);
router.use('/billing', billingRoutes);
router.use('/trust', trustRoutes);
router.use('/payments', paymentsRoutes);
router.use('/upload', uploadRoutes);
router.use('/spotify', spotifyRoutes);
router.use('/wimpy', wimpyRoutes);
router.use('/images', imagesRoutes);
// streaks route registered earlier
router.use('/email', emailRoutes);

module.exports = router;
